[package]
name = "changeset"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
cliclack = "0.3.4"
confy = "0.6.1"
extism = "1.6.0"
home = "0.5.9"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["blocking"] }
semver = "1.0.23"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sha256 = "1.5.0"

[profile.release]
lto = true

[profile.dev]
incremental = true

[lints.clippy]
needless-return = "allow"
